"""Code review agent using Claude Code SDK.

Based on the /code-review skill from Anthropic's claude-code plugins.
Runs autonomously to review a PR for bugs, CLAUDE.md compliance, and code quality.
"""

import logging

from claude_agent_sdk import ClaudeAgentOptions, query

from autopilot.agents.agent_logging import log_agent_message

CODE_REVIEW_PROMPT = """\
Provide a code review for pull request #{pr_number} in this repository.

To do this, follow these steps precisely:

1. Use `gh pr view {pr_number} --json title,body,state,isDraft,author,files` to check \
if the pull request (a) is closed, (b) is a draft, or (c) does not need a code review \
(e.g. because it is an automated pull request that is very simple and obviously ok). \
If so, respond with "SKIP" and explain why.

2. Find any relevant CLAUDE.md files from the codebase: the root CLAUDE.md file \
(if one exists), as well as any CLAUDE.md files in the directories whose files \
the pull request modified.

3. View the pull request diff with `gh pr diff {pr_number}`.

4. Review the changes for:
   a. Compliance with CLAUDE.md guidelines
   b. Obvious bugs (focus on large bugs, avoid nitpicks)
   c. Security vulnerabilities (SQL injection, XSS, command injection, etc.)
   d. Code quality issues that could cause problems in production

5. For each issue found, score it on a scale from 0-100 for confidence:
   - 0: False positive that doesn't stand up to scrutiny
   - 25: Might be real, might be false positive
   - 50: Real issue but minor/nitpick
   - 75: Very likely real, important, will impact functionality
   - 100: Definitely real, will happen frequently

6. Filter out any issues with a score less than 75.

7. Comment on the PR with your findings using:
   `gh pr comment {pr_number} --body "<comment>"`

   Format:
   ### Code review

   Found N issues:

   1. <brief description> (confidence: X/100)
      <link to file and line>

   Or if no issues:
   ### Code review
   No issues found. Checked for bugs, security, and CLAUDE.md compliance.

   End with: 🤖 Generated by VoxStore Autopilot

Examples of false positives to ignore:
- Pre-existing issues not introduced by this PR
- Issues a linter/typechecker would catch (CI runs those separately)
- General code quality unless explicitly required in CLAUDE.md
- Changes in functionality that are intentional
- Issues on lines not modified in this PR

Respond with a structured result:
- VERDICT: APPROVE or REQUEST_CHANGES
- ISSUES_COUNT: number of real issues found
- SUMMARY: 2-3 sentence summary
"""


async def run_code_review_agent(
    pr_number: str,
    repo_path: str,
    *,
    branch_name: str | None = None,
    logger: logging.Logger | None = None,
) -> dict:
    """Run the code review agent on a PR.

    Returns a dict with:
        - approved: bool
        - summary: str
    """
    log = logger or logging.getLogger("autopilot.review_agent")
    prompt = CODE_REVIEW_PROMPT.format(pr_number=pr_number)

    env: dict[str, str] = {}
    if branch_name:
        env["CLAUDE_CODE_TASK_LIST_ID"] = branch_name

    options = ClaudeAgentOptions(
        allowed_tools=["Read", "Glob", "Grep", "Bash"],
        cwd=repo_path,
        max_turns=20,
        permission_mode="bypassPermissions",
        env=env,
    )

    review_text: str = ""
    async for message in query(prompt=prompt, options=options):
        text = log_agent_message(message, log)
        if text:
            review_text = text

    approved = "APPROVE" in review_text.upper() and "REQUEST_CHANGES" not in review_text.upper()

    return {
        "approved": approved,
        "summary": review_text,
    }
